### PR TITLE
GetDigestAuthHeader should inherit proxy.

### PR DESCRIPTION
**Pull request by pedoc**
# Description

If the RestClient needs a proxy to access, this Authenticator will not work properly, and this function is completed by inheriting the proxy.

## Type of change

- [x] :sparkles: New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

nope.

### Attachments (if appropriate)

nope.

### Definition of Done

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Does this add new dependencies?

### CODE REVIEW

**Comment by bernardbr** [comment]
LGTM

**Comment by bernardbr** [comment]
Thanks for your contribution @pedoc <3!!!

**Comment by bernardbr** [comment]
@pedoc version 1.6.0 was released with your contributions. Thank you!

**Comment by pedoc** [comment]
thanks 😄

**Pull request merged**
